[build]
    publish     = "dist"
    functions   = "netlify/functions"
    command     = "npm run build"

[dev]
    autoLaunch  = true

    # netlify server port
    port         = 5555
    # webpack / react port
    # targetPort = 5555

[[edge_functions]]
  function = "index"
  path = "/*"

[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://localhost:8585"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

    # force = true set in redirect to send all requests to your function even if content is found.
    # As my root directory (public) has a index.html file, this file is served first without the 'force'
    # setting to true.